categories_final = {
    "Bathroom": [
        "Shampoo",
        "Conditioner",
        "Soap",
        "Hair dryer",
        "Towels",
        "Toilet paper",
        "Shower",
        "Bathtub",
        "Mirror",
        "Bidet",
    ],
    "Bedroom and laundry": [
        "Iron",
        "Ironing board",
        "Broom",
        "Vacuum cleaner",
        "Mop",
        "Trash can",
        "Cleaning supplies",
        "Clothes hangers",
        "Body soap",
        "Varia body soap",
        "Neutral body soap",
        "Cleaning products",
        "Drying rack for clothing",
        "Extra pillows and blankets",
        "clothing storage: walk-in closet",
        "Clothing storage: wardrobe",
        "Clothing storage: closet and dresser",
        "clothing storage: closet",
        "clothing storage",
        "wardrobe",
        "Washing machine",
        "washer",
        "free washerin unit",
        "Dryer",
        "Laundry basket",
        "Laundry detergent",
        "Fabric softener",
        "Clothes dryer",
        "Cleaning supplies",
        "Free dryer In unit",
        "Paid washer In unit",
        "Laundromat nearby",
        "Cleaning available during stay",
        "hangers",
        "Bed",
        "closet",
        "trash compactor",
    ],
    "Home Decor and Furniture": [
        "Sofa",
        "Couch",
        "Coffee table",
        "Bookshelf",
        "Lamps",
        "Curtains",
        "Rug",
        "Pictures",
        "Room-darkening shades",
        "Wine glasses",
        "Baking sheet",
        "Mirror",
        "Decorative items",
        "Clock",
    ],
    "Entertainment": [
        "TV",
        "Television",
        "Cable",
        "Streaming",
        "Sound system",
        "Projector",
        "Blu-ray",
        "Home theater",
        "Amazon Prime Video",
        "Standard cable",
        "record player",
        "disney+",
        "hbo max",
        "chromecast",
        "netflix",
        "record player",
        "dvd player",
        "roku",
        "game console",
        "hulu",
        "piano",
        "ping pong table",
        "arcade games",
        "Board games",
    ],
    "Family": [
        "Crib",
        "High chair",
        "Baby monitor",
        "Playpen",
        "Stroller",
        "Toys",
        "Diapers",
        "Baby bath",
        "Changing table",
        "Child safety lock",
        "Standalone high chair - available upon request",
        "Pack n play/Travel crib - available upon request",
        "Children's dinnerware",
        "Clamp on table seat high chair - always at the listing",
        "fire pit",
        "childrens playroom",
        "Fireplace",
        "Books and reading material",
        "Children's books and toys",
    ],
    "Heating and cooling": [
        "Fan",
        "Air conditioner",
        "Heater",
        "hot water",
        "heating",
        "ac - split type ductless system",
        "air conditioning",
        "central air conditioning",
        "central heating",
    ],
    "Home safety": [
        "Fire extinguisher",
        "Smoke detector",
        "Carbon monoxide detector",
        "First aid kit",
        "Security camera",
        "Lock",
        "Alarm system",
        "Carbon monoxide alarm",
        "Window guards",
        "Smoke alarm",
        "Keypad",
        "Smart lock",
        "private entrance",
        "Safe",
    ],
    "Internet and office": [
        "Wi-Fi",
        "wifi",
        "Internet",
        "Router",
        "Ethernet cable",
        "Modem",
        "Wi-Fi extender",
        "Smart home devices",
        "Bluetooth speaker",
        "Pocket wifi",
        "Ethernet connection",
        "Fast wifi (with specified Mbps speeds)",
        "Desk",
        "Work desk",
        "Alarm clock",
        "Dedicated workspace",
    ],
    "Kitchen and dining": [
        "Microwave",
        "kitchen",
        "Refrigerator",
        "mini fridge",
        "Freezer",
        "Oven",
        "Stove",
        "Dishwasher",
        "Coffee maker",
        "Toaster",
        "Rice maker",
        "Induction stove",
        "Gas stove",
        "Electric stove",
        "Stainless steel oven",
        "Teka stainless steel induction stove",
        "Otro electric stove",
        "Otro induction stove",
        "Franke electric stove",
        "dishes and silverware",
        "cooking basics",
        "childrens dinnerware",
        "blender",
        "french press",
        "Coffee",
        "Espresso machine",
        "Nespresso",
        "bread maker",
        "Dining table",
        "Chairs",
    ],
    "Parking and facilities": [
        "Shared gym in building",
        "exercise equipment: elliptical",
        "gym",
        "exercise equipment",
        "Stationary bike",
        "Treadmill",
        "Yoga mat",
        "Private gym nearby",
        "Elevator",
        "Shared gym in building",
        "Private gym nearby",
        "Paid parking garage on premises",
        "Paid parking lot off premises",
        "Free parking garage on premises",
        "Pet gate",
        "Parking",
        "Garage",
        "Driveway",
        "Bicycle rack",
        "Electric vehicle charger",
        "Carport",
        "Airport transfer",
        "Public transport nearby",
        "Paid parking garage on premises 1 space",
        "Paid parking lot off premises",
        "Free parking garage on premises 1 space",
        "EV charger",
        "Free street parking",
        "Outlet covers",
        "mosquito net",
    ],
    "Pet Care": [
        "Pet bed",
        "Food and water bowls",
        "Litter box",
        "Leash",
        "Pet toys",
        "Pet shampoo",
        "Pet carrier",
        "Pet food",
    ],
    "Services": [
        "Self check-in",
        "Pets allowed",
        "Long term stays allowed",
        "Luggage dropoff allowed",
        "Smoking allowed",
        "Host greets you",
        "Babysitter recommendations",
        "Private living room",
        "Beach essentials",
    ],
    "Scenic views": [
        "City skyline view",
        "Park view",
        "Mountain view",
        "Waterfront",
        "Lake view",
        "Ocean view",
        "Courtyard view",
        "Beach view",
        "sea view",
        "Bay view",
        "harbor view",
        "marina view",
    ],
    "Outdoor": [
        "Grill",
        "Barbecue",
        "Garden",
        "Patio",
        "Balcony",
        "Outdoor furniture",
        "Firepit",
        "Bicycles",
        "Kayak",
        "Pool",
        "Hot tub",
        "Outdoor playground",
        "Lake access",
        "Beach access",
        "Public or shared beach access",
        "Private backyard Fully fenced",
        "sun loungers",
        "outdoor dining area",
        "hammock",
        "backyard",
        "shared backyardnot fully fenced",
    ],
}
